### ISSUE TITLE
java中初始化

### ISSUE THREAD

**Issue by Samdogcom** [wufuqi123/WuKongAnimation#1]
<img width="927" alt="image" src="https://github.com/wufuqi123/WuKongAnimation/assets/11897814/d010458a-adc2-4f28-895b-a844b2252395">

java中初始化放在哪都提示错误

另外请问不能使用插值器吗?

**Comment by shijiannihao** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by wufuqi123** [comment]
sdk代码是kotlin写的，java调用静态使用 Action.INSTANCE.init()

**Comment by Samdogcom** [comment]
谢谢,一下没转过弯来
